/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountSignupRouteImport } from './routes/account/signup'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminRatesRouteImport } from './routes/admin/rates'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as OrderStatusOrderIdRouteImport } from './routes/order-status.$orderId'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as ApiAccountAddressesRouteImport } from './routes/api/account/addresses'
import { Route as ApiAccountCartRouteImport } from './routes/api/account/cart'
import { Route as ApiAccountCheckoutRouteImport } from './routes/api/account/checkout'
import { Route as ApiAccountOrdersRouteImport } from './routes/api/account/orders'
import { Route as ApiAccountProfileRouteImport } from './routes/api/account/profile'
import { Route as ApiAccountTrackingRouteImport } from './routes/api/account/tracking'
import { Route as ApiAccountWishlistRouteImport } from './routes/api/account/wishlist'
import { Route as ApiAdminAdminsRouteImport } from './routes/api/admin/admins'
import { Route as ApiAdminCustomersRouteImport } from './routes/api/admin/customers'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminInventoryRouteImport } from './routes/api/admin/inventory'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminProductsRouteImport } from './routes/api/admin/products'
import { Route as ApiAdminRatesRouteImport } from './routes/api/admin/rates'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiPaymentCreateRouteImport } from './routes/api/payment/create'
import { Route as ApiPaymentVerifyRouteImport } from './routes/api/payment/verify'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api/payment/webhook'
import { Route as ApiShippingWebhookRouteImport } from './routes/api/shipping/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSignupRoute = AccountSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRatesRoute = AdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusOrderIdRoute = OrderStatusOrderIdRouteImport.update({
  id: '/order-status/$orderId',
  path: '/order-status/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)
const ApiAccountAddressesRoute = ApiAccountAddressesRouteImport.update({
  id: '/api/account/addresses',
  path: '/api/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountCartRoute = ApiAccountCartRouteImport.update({
  id: '/api/account/cart',
  path: '/api/account/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountCheckoutRoute = ApiAccountCheckoutRouteImport.update({
  id: '/api/account/checkout',
  path: '/api/account/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountOrdersRoute = ApiAccountOrdersRouteImport.update({
  id: '/api/account/orders',
  path: '/api/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountTrackingRoute = ApiAccountTrackingRouteImport.update({
  id: '/api/account/tracking',
  path: '/api/account/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountWishlistRoute = ApiAccountWishlistRouteImport.update({
  id: '/api/account/wishlist',
  path: '/api/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAdminsRoute = ApiAdminAdminsRouteImport.update({
  id: '/api/admin/admins',
  path: '/api/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCustomersRoute = ApiAdminCustomersRouteImport.update({
  id: '/api/admin/customers',
  path: '/api/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInventoryRoute = ApiAdminInventoryRouteImport.update({
  id: '/api/admin/inventory',
  path: '/api/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProductsRoute = ApiAdminProductsRouteImport.update({
  id: '/api/admin/products',
  path: '/api/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRatesRoute = ApiAdminRatesRouteImport.update({
  id: '/api/admin/rates',
  path: '/api/admin/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreateRoute = ApiPaymentCreateRouteImport.update({
  id: '/api/payment/create',
  path: '/api/payment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentVerifyRoute = ApiPaymentVerifyRouteImport.update({
  id: '/api/payment/verify',
  path: '/api/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/api/payment/webhook',
  path: '/api/payment/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingWebhookRoute = ApiShippingWebhookRouteImport.update({
  id: '/api/shipping/webhook',
  path: '/api/shipping/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/enquire': typeof EnquireRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/products': typeof ApiProductsRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/account/addresses': typeof ApiAccountAddressesRoute
  '/api/account/cart': typeof ApiAccountCartRoute
  '/api/account/checkout': typeof ApiAccountCheckoutRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tracking': typeof ApiAccountTrackingRoute
  '/api/account/wishlist': typeof ApiAccountWishlistRoute
  '/api/admin/admins': typeof ApiAdminAdminsRoute
  '/api/admin/customers': typeof ApiAdminCustomersRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/rates': typeof ApiAdminRatesRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/shipping/webhook': typeof ApiShippingWebhookRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/enquire': typeof EnquireRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/products': typeof ApiProductsRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/account/addresses': typeof ApiAccountAddressesRoute
  '/api/account/cart': typeof ApiAccountCartRoute
  '/api/account/checkout': typeof ApiAccountCheckoutRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tracking': typeof ApiAccountTrackingRoute
  '/api/account/wishlist': typeof ApiAccountWishlistRoute
  '/api/admin/admins': typeof ApiAdminAdminsRoute
  '/api/admin/customers': typeof ApiAdminCustomersRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/rates': typeof ApiAdminRatesRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/shipping/webhook': typeof ApiShippingWebhookRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/enquire': typeof EnquireRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/products': typeof ApiProductsRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/account/addresses': typeof ApiAccountAddressesRoute
  '/api/account/cart': typeof ApiAccountCartRoute
  '/api/account/checkout': typeof ApiAccountCheckoutRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/tracking': typeof ApiAccountTrackingRoute
  '/api/account/wishlist': typeof ApiAccountWishlistRoute
  '/api/admin/admins': typeof ApiAdminAdminsRoute
  '/api/admin/customers': typeof ApiAdminCustomersRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/rates': typeof ApiAdminRatesRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/shipping/webhook': typeof ApiShippingWebhookRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/enquire'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/reset-password'
    | '/account/signup'
    | '/account/wishlist'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/rates'
    | '/admin/reports'
    | '/api/products'
    | '/order-status/$orderId'
    | '/account/'
    | '/admin/'
    | '/account/orders/$orderId'
    | '/api/account/addresses'
    | '/api/account/cart'
    | '/api/account/checkout'
    | '/api/account/orders'
    | '/api/account/profile'
    | '/api/account/tracking'
    | '/api/account/wishlist'
    | '/api/admin/admins'
    | '/api/admin/customers'
    | '/api/admin/dashboard'
    | '/api/admin/inventory'
    | '/api/admin/login'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/rates'
    | '/api/admin/session'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/payment/create'
    | '/api/payment/verify'
    | '/api/payment/webhook'
    | '/api/shipping/webhook'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/enquire'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/reset-password'
    | '/account/signup'
    | '/account/wishlist'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/rates'
    | '/admin/reports'
    | '/api/products'
    | '/order-status/$orderId'
    | '/account'
    | '/admin'
    | '/account/orders/$orderId'
    | '/api/account/addresses'
    | '/api/account/cart'
    | '/api/account/checkout'
    | '/api/account/orders'
    | '/api/account/profile'
    | '/api/account/tracking'
    | '/api/account/wishlist'
    | '/api/admin/admins'
    | '/api/admin/customers'
    | '/api/admin/dashboard'
    | '/api/admin/inventory'
    | '/api/admin/login'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/rates'
    | '/api/admin/session'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/payment/create'
    | '/api/payment/verify'
    | '/api/payment/webhook'
    | '/api/shipping/webhook'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/enquire'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/reset-password'
    | '/account/signup'
    | '/account/wishlist'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/rates'
    | '/admin/reports'
    | '/api/products'
    | '/order-status/$orderId'
    | '/account/'
    | '/admin/'
    | '/account/orders/$orderId'
    | '/api/account/addresses'
    | '/api/account/cart'
    | '/api/account/checkout'
    | '/api/account/orders'
    | '/api/account/profile'
    | '/api/account/tracking'
    | '/api/account/wishlist'
    | '/api/admin/admins'
    | '/api/admin/customers'
    | '/api/admin/dashboard'
    | '/api/admin/inventory'
    | '/api/admin/login'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/rates'
    | '/api/admin/session'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/payment/create'
    | '/api/payment/verify'
    | '/api/payment/webhook'
    | '/api/shipping/webhook'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  EnquireRoute: typeof EnquireRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiProductsRoute: typeof ApiProductsRoute
  OrderStatusOrderIdRoute: typeof OrderStatusOrderIdRoute
  ApiAccountAddressesRoute: typeof ApiAccountAddressesRoute
  ApiAccountCartRoute: typeof ApiAccountCartRoute
  ApiAccountCheckoutRoute: typeof ApiAccountCheckoutRoute
  ApiAccountOrdersRoute: typeof ApiAccountOrdersRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAccountTrackingRoute: typeof ApiAccountTrackingRoute
  ApiAccountWishlistRoute: typeof ApiAccountWishlistRoute
  ApiAdminAdminsRoute: typeof ApiAdminAdminsRoute
  ApiAdminCustomersRoute: typeof ApiAdminCustomersRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminInventoryRoute: typeof ApiAdminInventoryRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRoute
  ApiAdminProductsRoute: typeof ApiAdminProductsRoute
  ApiAdminRatesRoute: typeof ApiAdminRatesRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiPaymentCreateRoute: typeof ApiPaymentCreateRoute
  ApiPaymentVerifyRoute: typeof ApiPaymentVerifyRoute
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
  ApiShippingWebhookRoute: typeof ApiShippingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/signup': {
      id: '/account/signup'
      path: '/signup'
      fullPath: '/account/signup'
      preLoaderRoute: typeof AccountSignupRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rates': {
      id: '/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AdminRatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status/$orderId': {
      id: '/order-status/$orderId'
      path: '/order-status/$orderId'
      fullPath: '/order-status/$orderId'
      preLoaderRoute: typeof OrderStatusOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/account/addresses': {
      id: '/api/account/addresses'
      path: '/api/account/addresses'
      fullPath: '/api/account/addresses'
      preLoaderRoute: typeof ApiAccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/cart': {
      id: '/api/account/cart'
      path: '/api/account/cart'
      fullPath: '/api/account/cart'
      preLoaderRoute: typeof ApiAccountCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/checkout': {
      id: '/api/account/checkout'
      path: '/api/account/checkout'
      fullPath: '/api/account/checkout'
      preLoaderRoute: typeof ApiAccountCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/orders': {
      id: '/api/account/orders'
      path: '/api/account/orders'
      fullPath: '/api/account/orders'
      preLoaderRoute: typeof ApiAccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/tracking': {
      id: '/api/account/tracking'
      path: '/api/account/tracking'
      fullPath: '/api/account/tracking'
      preLoaderRoute: typeof ApiAccountTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/wishlist': {
      id: '/api/account/wishlist'
      path: '/api/account/wishlist'
      fullPath: '/api/account/wishlist'
      preLoaderRoute: typeof ApiAccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/admins': {
      id: '/api/admin/admins'
      path: '/api/admin/admins'
      fullPath: '/api/admin/admins'
      preLoaderRoute: typeof ApiAdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/customers': {
      id: '/api/admin/customers'
      path: '/api/admin/customers'
      fullPath: '/api/admin/customers'
      preLoaderRoute: typeof ApiAdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/inventory': {
      id: '/api/admin/inventory'
      path: '/api/admin/inventory'
      fullPath: '/api/admin/inventory'
      preLoaderRoute: typeof ApiAdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products': {
      id: '/api/admin/products'
      path: '/api/admin/products'
      fullPath: '/api/admin/products'
      preLoaderRoute: typeof ApiAdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/rates': {
      id: '/api/admin/rates'
      path: '/api/admin/rates'
      fullPath: '/api/admin/rates'
      preLoaderRoute: typeof ApiAdminRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/create': {
      id: '/api/payment/create'
      path: '/api/payment/create'
      fullPath: '/api/payment/create'
      preLoaderRoute: typeof ApiPaymentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/verify': {
      id: '/api/payment/verify'
      path: '/api/payment/verify'
      fullPath: '/api/payment/verify'
      preLoaderRoute: typeof ApiPaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook': {
      id: '/api/payment/webhook'
      path: '/api/payment/webhook'
      fullPath: '/api/payment/webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping/webhook': {
      id: '/api/shipping/webhook'
      path: '/api/shipping/webhook'
      fullPath: '/api/shipping/webhook'
      preLoaderRoute: typeof ApiShippingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSignupRoute: typeof AccountSignupRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSignupRoute: AccountSignupRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRatesRoute: typeof AdminRatesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRatesRoute: AdminRatesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  EnquireRoute: EnquireRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiProductsRoute: ApiProductsRoute,
  OrderStatusOrderIdRoute: OrderStatusOrderIdRoute,
  ApiAccountAddressesRoute: ApiAccountAddressesRoute,
  ApiAccountCartRoute: ApiAccountCartRoute,
  ApiAccountCheckoutRoute: ApiAccountCheckoutRoute,
  ApiAccountOrdersRoute: ApiAccountOrdersRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAccountTrackingRoute: ApiAccountTrackingRoute,
  ApiAccountWishlistRoute: ApiAccountWishlistRoute,
  ApiAdminAdminsRoute: ApiAdminAdminsRoute,
  ApiAdminCustomersRoute: ApiAdminCustomersRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminInventoryRoute: ApiAdminInventoryRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRoute,
  ApiAdminProductsRoute: ApiAdminProductsRoute,
  ApiAdminRatesRoute: ApiAdminRatesRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiPaymentCreateRoute: ApiPaymentCreateRoute,
  ApiPaymentVerifyRoute: ApiPaymentVerifyRoute,
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
  ApiShippingWebhookRoute: ApiShippingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
